apiVersion: v1
kind: Service
metadata:
  name: go-reminders
  labels:
    app: go-reminders
spec:
  type: NodePort
  selector:
    app: go-reminders
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30080
  externalTrafficPolicy: Cluster
