#
# Copyright 2015-2019 VMware, Inc. All Rights Reserved.
# Author: Tom Hite (thite@vmware.com)
#
# SPDX-License-Identifier: https://spdx.org/licenses/MIT.html
#

apiVersion: v1
kind: Service
metadata:
  name: py-reminders
  labels:
    app: py-reminders
spec:
  type: ClusterIP
  selector:
    app: py-reminders
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
